# Generated by Django 5.2.3 on 2025-06-21 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invited_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invited_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
