# Generated by Django 5.2.3 on 2025-06-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_user_invitation_invited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_taken_gift",
            field=models.BooleanField(default=False),
        ),
    ]
